[build]
  command = "npm install && npm install tailwindcss postcss autoprefixer @vitejs/plugin-react @tanstack/react-query drizzle-orm drizzle-zod --save && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"